apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: mail-operator-app
    appstudio.openshift.io/component: mail-operator-fbc-component
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: mail-operator-fbc-component
  namespace: managed-release-team-tenant
spec:
  git_provider:
    secret:
      key: github.token
      name: pipelines-as-code-secret
    webhook_secret:
      key: https___github.com_theflockers_mail-operator-app
      name: pipelines-as-code-webhooks-secret
  url: https://github.com/theflockers/mail-operator-app
