apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mail-operator-fbc-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mail-operator-component
    app.kubernetes.io/part-of: mail-operator-app
  name: mail-operator-fbc-component
  namespace: managed-release-team-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mail-operator-fbc-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: mail-operator-fbc-component
    spec:
      containers:
      - image: quay.io/lmendes/user-workload@sha256:2685246e4cd7458ad68a7231a27d336696d31e523050e4cb6cec27edd2ef3e5a
        imagePullPolicy: Always
        name: container-image
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
